/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMemberRouteImport } from './routes/_authenticated/member'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMemberIndexRouteImport } from './routes/_authenticated/member.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedMemberTasksRouteImport } from './routes/_authenticated/member.tasks'
import { Route as AuthenticatedMemberSettingsRouteImport } from './routes/_authenticated/member.settings'
import { Route as AuthenticatedMemberReportsRouteImport } from './routes/_authenticated/member.reports'
import { Route as AuthenticatedMemberProjectsRouteImport } from './routes/_authenticated/member.projects'
import { Route as AuthenticatedMemberProfileRouteImport } from './routes/_authenticated/member.profile'
import { Route as AuthenticatedMemberNotificationsRouteImport } from './routes/_authenticated/member.notifications'
import { Route as AuthenticatedAdminTasksRouteImport } from './routes/_authenticated/admin.tasks'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin.projects'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin.members'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminAiInsightsRouteImport } from './routes/_authenticated/admin.ai-insights'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMemberRoute = AuthenticatedMemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMemberIndexRoute =
  AuthenticatedMemberIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMemberRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedMemberTasksRoute =
  AuthenticatedMemberTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedMemberRoute,
  } as any)
const AuthenticatedMemberSettingsRoute =
  AuthenticatedMemberSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedMemberRoute,
  } as any)
const AuthenticatedMemberReportsRoute =
  AuthenticatedMemberReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedMemberRoute,
  } as any)
const AuthenticatedMemberProjectsRoute =
  AuthenticatedMemberProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedMemberRoute,
  } as any)
const AuthenticatedMemberProfileRoute =
  AuthenticatedMemberProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedMemberRoute,
  } as any)
const AuthenticatedMemberNotificationsRoute =
  AuthenticatedMemberNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedMemberRoute,
  } as any)
const AuthenticatedAdminTasksRoute = AuthenticatedAdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAiInsightsRoute =
  AuthenticatedAdminAiInsightsRouteImport.update({
    id: '/ai-insights',
    path: '/ai-insights',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/member': typeof AuthenticatedMemberRouteWithChildren
  '/admin/ai-insights': typeof AuthenticatedAdminAiInsightsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/member/notifications': typeof AuthenticatedMemberNotificationsRoute
  '/member/profile': typeof AuthenticatedMemberProfileRoute
  '/member/projects': typeof AuthenticatedMemberProjectsRoute
  '/member/reports': typeof AuthenticatedMemberReportsRoute
  '/member/settings': typeof AuthenticatedMemberSettingsRoute
  '/member/tasks': typeof AuthenticatedMemberTasksRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/member/': typeof AuthenticatedMemberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/ai-insights': typeof AuthenticatedAdminAiInsightsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/member/notifications': typeof AuthenticatedMemberNotificationsRoute
  '/member/profile': typeof AuthenticatedMemberProfileRoute
  '/member/projects': typeof AuthenticatedMemberProjectsRoute
  '/member/reports': typeof AuthenticatedMemberReportsRoute
  '/member/settings': typeof AuthenticatedMemberSettingsRoute
  '/member/tasks': typeof AuthenticatedMemberTasksRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/member': typeof AuthenticatedMemberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/member': typeof AuthenticatedMemberRouteWithChildren
  '/_authenticated/admin/ai-insights': typeof AuthenticatedAdminAiInsightsRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/_authenticated/member/notifications': typeof AuthenticatedMemberNotificationsRoute
  '/_authenticated/member/profile': typeof AuthenticatedMemberProfileRoute
  '/_authenticated/member/projects': typeof AuthenticatedMemberProjectsRoute
  '/_authenticated/member/reports': typeof AuthenticatedMemberReportsRoute
  '/_authenticated/member/settings': typeof AuthenticatedMemberSettingsRoute
  '/_authenticated/member/tasks': typeof AuthenticatedMemberTasksRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/member/': typeof AuthenticatedMemberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/login'
    | '/signup'
    | '/admin'
    | '/member'
    | '/admin/ai-insights'
    | '/admin/analytics'
    | '/admin/members'
    | '/admin/notifications'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/tasks'
    | '/member/notifications'
    | '/member/profile'
    | '/member/projects'
    | '/member/reports'
    | '/member/settings'
    | '/member/tasks'
    | '/admin/'
    | '/member/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/login'
    | '/signup'
    | '/admin/ai-insights'
    | '/admin/analytics'
    | '/admin/members'
    | '/admin/notifications'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/tasks'
    | '/member/notifications'
    | '/member/profile'
    | '/member/projects'
    | '/member/reports'
    | '/member/settings'
    | '/member/tasks'
    | '/admin'
    | '/member'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/features'
    | '/login'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/member'
    | '/_authenticated/admin/ai-insights'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/tasks'
    | '/_authenticated/member/notifications'
    | '/_authenticated/member/profile'
    | '/_authenticated/member/projects'
    | '/_authenticated/member/reports'
    | '/_authenticated/member/settings'
    | '/_authenticated/member/tasks'
    | '/_authenticated/admin/'
    | '/_authenticated/member/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/member': {
      id: '/_authenticated/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof AuthenticatedMemberRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/member/': {
      id: '/_authenticated/member/'
      path: '/'
      fullPath: '/member/'
      preLoaderRoute: typeof AuthenticatedMemberIndexRouteImport
      parentRoute: typeof AuthenticatedMemberRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/member/tasks': {
      id: '/_authenticated/member/tasks'
      path: '/tasks'
      fullPath: '/member/tasks'
      preLoaderRoute: typeof AuthenticatedMemberTasksRouteImport
      parentRoute: typeof AuthenticatedMemberRoute
    }
    '/_authenticated/member/settings': {
      id: '/_authenticated/member/settings'
      path: '/settings'
      fullPath: '/member/settings'
      preLoaderRoute: typeof AuthenticatedMemberSettingsRouteImport
      parentRoute: typeof AuthenticatedMemberRoute
    }
    '/_authenticated/member/reports': {
      id: '/_authenticated/member/reports'
      path: '/reports'
      fullPath: '/member/reports'
      preLoaderRoute: typeof AuthenticatedMemberReportsRouteImport
      parentRoute: typeof AuthenticatedMemberRoute
    }
    '/_authenticated/member/projects': {
      id: '/_authenticated/member/projects'
      path: '/projects'
      fullPath: '/member/projects'
      preLoaderRoute: typeof AuthenticatedMemberProjectsRouteImport
      parentRoute: typeof AuthenticatedMemberRoute
    }
    '/_authenticated/member/profile': {
      id: '/_authenticated/member/profile'
      path: '/profile'
      fullPath: '/member/profile'
      preLoaderRoute: typeof AuthenticatedMemberProfileRouteImport
      parentRoute: typeof AuthenticatedMemberRoute
    }
    '/_authenticated/member/notifications': {
      id: '/_authenticated/member/notifications'
      path: '/notifications'
      fullPath: '/member/notifications'
      preLoaderRoute: typeof AuthenticatedMemberNotificationsRouteImport
      parentRoute: typeof AuthenticatedMemberRoute
    }
    '/_authenticated/admin/tasks': {
      id: '/_authenticated/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AuthenticatedAdminTasksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai-insights': {
      id: '/_authenticated/admin/ai-insights'
      path: '/ai-insights'
      fullPath: '/admin/ai-insights'
      preLoaderRoute: typeof AuthenticatedAdminAiInsightsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAiInsightsRoute: typeof AuthenticatedAdminAiInsightsRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTasksRoute: typeof AuthenticatedAdminTasksRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAiInsightsRoute: AuthenticatedAdminAiInsightsRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTasksRoute: AuthenticatedAdminTasksRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedMemberRouteChildren {
  AuthenticatedMemberNotificationsRoute: typeof AuthenticatedMemberNotificationsRoute
  AuthenticatedMemberProfileRoute: typeof AuthenticatedMemberProfileRoute
  AuthenticatedMemberProjectsRoute: typeof AuthenticatedMemberProjectsRoute
  AuthenticatedMemberReportsRoute: typeof AuthenticatedMemberReportsRoute
  AuthenticatedMemberSettingsRoute: typeof AuthenticatedMemberSettingsRoute
  AuthenticatedMemberTasksRoute: typeof AuthenticatedMemberTasksRoute
  AuthenticatedMemberIndexRoute: typeof AuthenticatedMemberIndexRoute
}

const AuthenticatedMemberRouteChildren: AuthenticatedMemberRouteChildren = {
  AuthenticatedMemberNotificationsRoute: AuthenticatedMemberNotificationsRoute,
  AuthenticatedMemberProfileRoute: AuthenticatedMemberProfileRoute,
  AuthenticatedMemberProjectsRoute: AuthenticatedMemberProjectsRoute,
  AuthenticatedMemberReportsRoute: AuthenticatedMemberReportsRoute,
  AuthenticatedMemberSettingsRoute: AuthenticatedMemberSettingsRoute,
  AuthenticatedMemberTasksRoute: AuthenticatedMemberTasksRoute,
  AuthenticatedMemberIndexRoute: AuthenticatedMemberIndexRoute,
}

const AuthenticatedMemberRouteWithChildren =
  AuthenticatedMemberRoute._addFileChildren(AuthenticatedMemberRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMemberRoute: typeof AuthenticatedMemberRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMemberRoute: AuthenticatedMemberRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
